version: "3.7"

services:
  sut:
    depends_on:
      - sunrisa_server
    build:
      context: "."
      dockerfile: "Dockerfile.integration"
    container_name: sunrisa_integration
    image: sunrisa_integration
    environment:
      - PYTHONUNBUFFERED=1
  sunrisa_server:
    depends_on:
      - db
    build: .
    ports:
      - '5000:5000'
    expose:
      # Opens port 5000 on the container
      - '5000'
    container_name: sunrisa-server-container
    image: sunrisa_server
    environment:
      - PYTHONUNBUFFERED=1
  db:
    image: mysql:5.7
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root


volumes:
  db_data: {}
